services:
  triton:
    build:
      context: .
      dockerfile: Dockerfile.triton
    shm_size: '4gb'
    volumes:
      - ${PWD}/models:/models
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v2/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 2
    command: tritonserver --model-repository=/models 
